# Site settings
title: Bill Keys 
description: I am an experienced software developer working at Saint Michael's College
baseurl: "" # the subpath of your site, e.g. /blog
url: "billkeys.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Bill Keys
user_description: I am an experienced software developer working at Saint Michael's College
user_title: Software Developer
email: william.keys1@gmail.com 
twitter_username: bk_keys
github_username:  billKeys

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
